# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SelfAwareness' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SelfAwareness
  pod 'ViewAnimator'

end

target 'SelfAwareness WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SelfAwareness WatchKit App

end

target 'SelfAwareness WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SelfAwareness WatchKit Extension

end
